name: Lee-QAT-TLS-handshake-acceleration-for-Istio.yaml-copy
services:
  Cluster Role Binding:
    name: Cluster Role Binding
    type: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    version: v1.25.2
    model: kubernetes
    traits:
      meshmap:
        edges: []
        id: 66e81770-e9b2-4623-9f7a-9db6affb96bf
        label: Cluster Role Binding
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Kubernetes
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
            svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
          name: kubernetes
          version: v1.25.2
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px","width":"16px","padding":"6px", "z-index":9999}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrolebinding-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrolebinding-white.svg
        position:
          posX: 448.736715599411
          posY: 79.02882289314847
  SA-istio-operator:
    name: SA-istio-operator
    type: ServiceAccount
    apiVersion: v1
    namespace: default
    model: kubernetes
    traits:
      meshmap:
        edges: []
        id: 9240267f-d393-4c5d-bdf9-596bacf0ebf0
        label: SA-istio-operator
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: ""
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
        position:
          posX: 715.4802112989335
          posY: 228.4359846293381
  default:
    name: default
    type: Namespace
    apiVersion: v1
    namespace: default
    version: v1.25.2
    model: kubernetes
    traits:
      meshmap:
        edges: []
        id: 4c61a014-839c-4a46-ba51-c0945a9f5412
        label: default
        position:
          posX: 697.0227610473714
          posY: 56.579499647640475
  example-istiocontrolplane:
    name: example-istiocontrolplane
    type: IstioOperator
    apiVersion: install.istio.io/v1alpha1
    namespace: default
    model: istio-base
    dependsOn:
    - default
    settings:
      spec:
        components:
          egress Gateways:
          - enabled: true
            name: istio-egressgateway
          ingress Gateways:
          - enabled: true
            k8s:
              pod Annotations:
                proxy.istio.io/config: |
                  privateKeyProvider:
                    qat:
                      pollDelay: 10ms
            name: istio-ingressgateway
        profile: demo
    traits:
      meshmap:
        edges: []
        id: 0a9190c6-3b94-4497-9b5e-0e26e26a3f4a
        label: example-istiocontrolplane
        meshmodel-metadata:
          isCustomResource: true
          isNamespaced: true
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: circle
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        parent: 4c61a014-839c-4a46-ba51-c0945a9f5412
        position:
          posX: 670.2161210949191
          posY: 64.03933740008372
  intel-qat-plugin:
    name: intel-qat-plugin
    type: DaemonSet
    apiVersion: apps/v1
    namespace: qat-device-plugin
    model: kubernetes
    settings:
      spec:
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            app: intel-qat-plugin
        template:
          metadata:
            annotations:
              container.apparmor.security.beta.kubernetes.io/intel-qat-plugin: unconfined
            labels:
              app: intel-qat-plugin
          spec:
            automountServiceAccountToken: false
            containers:
            - image: intel/intel-qat-plugin:0.25.0
              imagePullPolicy: IfNotPresent
              name: intel-qat-plugin
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                seLinuxOptions:
                  type: container_device_plugin_t
              volumeMounts:
              - mountPath: /dev/vfio
                name: devdir
                readOnly: true
              - mountPath: /sys/kernel/debug
                name: debugfsdir
                readOnly: true
              - mountPath: /sys/bus/pci
                name: pcidir
              - mountPath: /var/lib/kubelet/device-plugins
                name: kubeletsockets
            dnsPolicy: ClusterFirst
            nodeSelector:
              kubernetes.io/arch: amd64
            restartPolicy: Always
            schedulerName: default-scheduler
            volumes:
            - hostPath:
                path: /dev/vfio
                type: ""
              name: devdir
            - hostPath:
                path: /sys/kernel/debug
                type: ""
              name: debugfsdir
            - hostPath:
                path: /sys/bus/pci
                type: ""
              name: pcidir
            - hostPath:
                path: /var/lib/kubelet/device-plugins
                type: ""
              name: kubeletsockets
        updateStrategy:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
          type: RollingUpdate
    traits:
      meshmap:
        edges: []
        id: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c2
        label: intel-qat-plugin
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: true
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          styleOverrides: '{"background-image":"none","border-width":2,"background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/daemonset-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/daemonset-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/daemonset-color.svg
        position:
          posX: 282.8423681046338
          posY: 240.22314913106615
  istio-operator-blxnk:
    name: istio-operator
    type: Service
    apiVersion: v1
    namespace: default
    model: kubernetes
    settings:
      spec:
        ports:
        - name: http-metrics
          node Port: 33285
          port: 8080
          protocol: TCP
          target Port: 8383
        - node Port: 39238
          port: 80
          protocol: TCP
        - port: 8080
          protocol: TCP
        selector:
          name: istio-operator
    traits:
      meshmap:
        edges:
        - data:
            id: cddec786-134e-4c0f-9745-6818509d642c
            metadata:
              port: 80
              protocol: TCP
            source: d24ca3fc-fb37-40d6-86b7-a2665b24f120
            subType: Network
            target: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c1
        - data:
            id: 7729d915-9db8-4de7-919c-239abdb9825f
            metadata:
              port: 8080
              protocol: TCP
            source: d24ca3fc-fb37-40d6-86b7-a2665b24f120
            subType: Network
            target: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c1
        - data:
            id: 25406e5b-555d-407a-b7df-e4595b746af9
            metadata: 66e81770-e9b2-4623-9f7a-9db6affb96bf
            source: f9e95f4b-ffef-4523-917c-1442bb59b53b
            subType: Permission
            target: d24ca3fc-fb37-40d6-86b7-a2665b24f120
        id: d24ca3fc-fb37-40d6-86b7-a2665b24f120
        label: istio-operator
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          styleOverrides: '{"height":16,"width":17,"padding":12,"background-fit":"none","background-position-y":4.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        position:
          posX: 544.9229890481672
          posY: 102.815490256573
  istio-operator-eukiz:
    name: istio-operator
    type: Deployment
    apiVersion: apps/v1
    namespace: default
    model: kubernetes
    dependsOn:
    - default
    settings:
      spec:
        replicas: 1
        revision History Limit: 10
        selector:
          match Labels:
            name: istio-operator
        template:
          metadata:
            annotations:
              prometheus.io/port: "15014"
              prometheus.io/scrape: "true"
            labels:
              name: istio-operator
          spec:
            containers:
            - command:
              - operator
              - server
              - --monitoring-host=127.0.0.1
              - --monitoring-port=15014
              env:
              - name: WATCH_NAMESPACE
                value: istio-system
              - name: LEADER_ELECTION_NAMESPACE
                value: istio-operator
              - name: POD_NAME
                value From:
                  field Ref:
                    field Path: metadata.name
              - name: OPERATOR_NAME
                value: istio-operator
              - name: WAIT_FOR_RESOURCES_TIMEOUT
                value: 300s
              - name: REVISION
                value: ""
              image: docker.io/istio/operator:1.18.0
              name: istio-operator
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
              security Context:
                allow Privilege Escalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                read Only Root Filesystem: true
                run As Group: 1337
                run As Non Root: true
                run As User: 1337
            service Account Name: istio-operator
    traits:
      meshmap:
        edges:
        - data:
            id: cddec786-134e-4c0f-9745-6818509d642c
            metadata:
              port: 80
              protocol: TCP
            source: d24ca3fc-fb37-40d6-86b7-a2665b24f120
            subType: Network
            target: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c1
        - data:
            id: 7729d915-9db8-4de7-919c-239abdb9825f
            metadata:
              port: 8080
              protocol: TCP
            source: d24ca3fc-fb37-40d6-86b7-a2665b24f120
            subType: Network
            target: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c1
        id: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c1
        label: istio-operator
        parent: 4c61a014-839c-4a46-ba51-c0945a9f5412
        position:
          posX: 724.3294009998236
          posY: 31.119661895197233
  istio-operator-uqaia:
    name: istio-operator
    type: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    model: kubernetes
    settings:
      rules:
      - api Groups:
        - authentication.istio.io
        resources:
        - Service
        verbs:
        - get
      - api Groups:
        - config.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - install.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - networking.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - security.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - admissionregistration.k8s.io
        resources:
        - mutatingwebhookconfigurations
        - validatingwebhookconfigurations
        verbs:
        - '*'
      - api Groups:
        - apiextensions.k8s.io
        resources:
        - customresourcedefinitions.apiextensions.k8s.io
        - customresourcedefinitions
        verbs:
        - '*'
      - api Groups:
        - apps
        - extensions
        resources:
        - daemonsets
        - deployments
        - deployments/finalizers
        - replicasets
        verbs:
        - '*'
      - api Groups:
        - autoscaling
        resources:
        - horizontalpodautoscalers
        verbs:
        - '*'
      - api Groups:
        - monitoring.coreos.com
        resources:
        - servicemonitors
        verbs:
        - get
        - create
        - update
      - api Groups:
        - policy
        resources:
        - poddisruptionbudgets
        verbs:
        - '*'
      - api Groups:
        - rbac.authorization.k8s.io
        resources:
        - clusterrolebindings
        - clusterroles
        - roles
        - rolebindings
        verbs:
        - '*'
      - api Groups:
        - coordination.k8s.io
        resources:
        - leases
        verbs:
        - get
        - create
        - update
      - api Groups:
        - ""
        resources:
        - configmaps
        - endpoints
        - events
        - namespaces
        - pods
        - pods/proxy
        - pods/portforward
        - persistentvolumeclaims
        - secrets
        - services
        - serviceaccounts
        - resourcequotas
        verbs:
        - '*'
    traits:
      meshmap:
        edges:
        - data:
            id: 25406e5b-555d-407a-b7df-e4595b746af9
            metadata: 66e81770-e9b2-4623-9f7a-9db6affb96bf
            source: f9e95f4b-ffef-4523-917c-1442bb59b53b
            subType: Permission
            target: d24ca3fc-fb37-40d6-86b7-a2665b24f120
        id: f9e95f4b-ffef-4523-917c-1442bb59b53b
        label: istio-operator
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px","width":"16px","padding":"6px"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrole-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrole-white.svg
        position:
          posX: 316.1300720820455
          posY: 101.28988080000929
