name: GuestBook App
services:
  comment-ak:
    name: comment-ak
    type: Comment
    apiVersion: core.meshery.io/v1alpha1
    version: v1.0.0
    model: meshery
    settings:
      user Messages: []
    traits:
      meshmap:
        id: 00a1c0c2-f416-418f-953d-2c93743cbd86
        label: comment-ak
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Meshery
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/meshery/color/broker-color.svg
            svgWhite: ui/public/static/img/meshmodels/aws-node-termination-handler-2/white/terminator-white.svg
          name: meshery
          version: v1.0.0
        meshmodel-metadata:
          genealogy: ""
          isAnnotation: true
          isNamespaced: false
          logoURL: ""
          model: meshery
          modelDisplayName: Meshery
          primaryColor: '#FFDE00'
          published: true
          secondaryColor: '#FFDE00'
          shape: tag
          styleOverrides: '{"height":"22px","width":"22px","x":"3.5px","y":"3.5px"}'
          subCategory: App Definition and Development
          svgColor: ui/public/static/img/meshmodels/meshery/color/comment-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/meshery/color/comment-color.svg
        position:
          posX: 347.0257008929924
          posY: 437.85666855084844
        style: []
        whiteboardData: {}
  comment-if:
    name: comment-if
    type: Comment
    apiVersion: core.meshery.io/v1alpha1
    version: v1.0.0
    model: meshery
    traits:
      meshmap:
        id: 4d148de8-d618-4a83-ab2e-d02b7ad97e7a
        label: comment-if
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Meshery
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/meshery/color/broker-color.svg
            svgWhite: ui/public/static/img/meshmodels/aws-node-termination-handler-2/white/terminator-white.svg
          name: meshery
          version: v1.0.0
        meshmodel-metadata:
          genealogy: ""
          isAnnotation: true
          isNamespaced: false
          logoURL: ""
          model: meshery
          modelDisplayName: Meshery
          primaryColor: '#FFDE00'
          published: true
          secondaryColor: '#FFDE00'
          shape: tag
          styleOverrides: '{"height":"22px","width":"22px","x":"3.5px","y":"3.5px"}'
          subCategory: App Definition and Development
          svgColor: ui/public/static/img/meshmodels/meshery/color/comment-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/meshery/color/comment-color.svg
        position:
          posX: 166.19411922770138
          posY: 276.63799174280916
        style: []
        whiteboardData:
          style: {}
  frontend-bhbbq:
    name: frontend
    type: Deployment
    apiVersion: apps/v1
    namespace: guestbook
    model: kubernetes
    dependsOn:
    - guestbook
    settings:
      spec:
        replicas: 3
        selector:
          match Labels:
            app: guestbook
            tier: frontend
        template:
          metadata:
            labels:
              app: guestbook
              tier: frontend
          spec:
            containers:
            - env:
              - name: GET_HOSTS_FROM
                value: dns
              image: gcr.io/google_samples/gb-frontend:v5
              name: php-redis
              ports:
              - container Port: 80
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
    traits:
      meshmap:
        id: 43a7b935-6109-4f5c-84fb-5e3454f9c6d1
        label: frontend
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: true
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          styleOverrides: '{"background-image":"none","border-width":2,"background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
        parent: 1e3a8397-8740-49ab-8591-d8276626c023
        position:
          posX: 235.12164554015538
          posY: 268.87880477631523
        style:
        - data:
            id: 54a87987-08e0-481a-9ea1-2110f1eaed34
            metadata:
              port: 80
              protocol: TCP
            source: 4ae55da0-82eb-405e-9410-75623cee1043
            subType: Network
            target: 43a7b935-6109-4f5c-84fb-5e3454f9c6d1
        whiteboardData: {}
  frontend-rvdkf:
    name: frontend
    type: Service
    apiVersion: v1
    model: kubernetes
    dependsOn:
    - guestbook
    settings:
      spec:
        ports:
        - port: 80
          protocol: TCP
        - port: 80
          protocol: TCP
        selector:
          app: guestbook
          tier: frontend
    traits:
      meshmap:
        id: 4ae55da0-82eb-405e-9410-75623cee1043
        label: frontend
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          styleOverrides: '{"height":16,"width":17,"padding":12,"background-fit":"none","background-position-y":4.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        parent: 1e3a8397-8740-49ab-8591-d8276626c023
        position:
          posX: 331.6120963395104
          posY: 267.75993465422613
        style:
        - data:
            id: 54a87987-08e0-481a-9ea1-2110f1eaed34
            metadata:
              port: 80
              protocol: TCP
            source: 4ae55da0-82eb-405e-9410-75623cee1043
            subType: Network
            target: 43a7b935-6109-4f5c-84fb-5e3454f9c6d1
        whiteboardData:
          style: {}
  guestbook:
    name: guestbook
    type: Namespace
    apiVersion: v1
    namespace: default
    model: kubernetes
    traits:
      meshmap:
        id: 1e3a8397-8740-49ab-8591-d8276626c023
        label: guestbook
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: false
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: rectangle
          styleOverrides: '{"background-image":"none","border-width":2,"border-style":"dashed","background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/namespace-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/namespace-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/namespace-color.svg
        position:
          posX: 431.89603688390287
          posY: 276.9478517126388
        style: []
        whiteboardData: {}
  redis-follower-gqrje:
    name: redis-follower
    type: Service
    apiVersion: v1
    namespace: guestbook
    model: kubernetes
    dependsOn:
    - guestbook
    settings:
      spec:
        ports:
        - port: 6379
          protocol: TCP
        - port: 6379
          protocol: TCP
        selector:
          app: redis
          role: follower
          tier: backend
    traits:
      meshmap:
        id: 7e403128-5022-409a-a1f2-26e0a5d25685
        label: redis-follower
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          styleOverrides: '{"height":16,"width":17,"padding":12,"background-fit":"none","background-position-y":4.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        parent: 1e3a8397-8740-49ab-8591-d8276626c023
        position:
          posX: 528.4730476564175
          posY: 175.33022298565365
        style:
        - data:
            id: f1055812-fc3a-40cd-89a9-10850b6f91ac
            metadata:
              port: 6379
              protocol: TCP
            source: 7e403128-5022-409a-a1f2-26e0a5d25685
            subType: Network
            target: 9407d316-5e5a-4212-8767-2bcd60c9ac17
        - data:
            id: 6985e17c-d4c0-4600-94ed-4809afe3df6f
            metadata:
              port: 6379
              protocol: TCP
            source: 7e403128-5022-409a-a1f2-26e0a5d25685
            subType: Network
            target: a6361bc8-7f4e-4e11-9406-e1bfd5578a53
        whiteboardData:
          style: {}
  redis-follower-gwiei:
    name: redis-follower
    type: Deployment
    apiVersion: apps/v1
    namespace: guestbook
    model: kubernetes
    dependsOn:
    - guestbook
    settings:
      spec:
        replicas: 2
        selector:
          match Labels:
            app: redis
        template:
          metadata:
            labels:
              app: redis
              role: follower
              tier: backend
          spec:
            containers:
            - image: gcr.io/google_samples/gb-redis-follower:v2
              name: follower
              ports:
              - container Port: 6379
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
    traits:
      meshmap:
        id: 9407d316-5e5a-4212-8767-2bcd60c9ac17
        label: redis-follower
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: true
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          styleOverrides: '{"background-image":"none","border-width":2,"background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
        parent: 1e3a8397-8740-49ab-8591-d8276626c023
        position:
          posX: 435.97113886518787
          posY: 269.25669870235447
        style:
        - data:
            id: c586a713-2ded-42b5-8dba-51bda8f2be08
            metadata:
              port: 6379
              protocol: TCP
            source: 6badde68-595b-4e86-9be8-61318e52b476
            subType: Network
            target: 9407d316-5e5a-4212-8767-2bcd60c9ac17
        - data:
            id: f1055812-fc3a-40cd-89a9-10850b6f91ac
            metadata:
              port: 6379
              protocol: TCP
            source: 7e403128-5022-409a-a1f2-26e0a5d25685
            subType: Network
            target: 9407d316-5e5a-4212-8767-2bcd60c9ac17
        whiteboardData: {}
  redis-leader-acgpu:
    name: redis-leader
    type: Deployment
    apiVersion: apps/v1
    namespace: guestbook
    model: kubernetes
    dependsOn:
    - guestbook
    settings:
      spec:
        replicas: 1
        selector:
          match Labels:
            app: redis
        template:
          metadata:
            labels:
              app: redis
              role: leader
              tier: backend
          spec:
            containers:
            - image: docker.io/redis:6.0.5
              name: leader
              ports:
              - container Port: 6379
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
    traits:
      meshmap:
        id: a6361bc8-7f4e-4e11-9406-e1bfd5578a53
        label: redis-leader
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: true
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          styleOverrides: '{"background-image":"none","border-width":2,"background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
        parent: 1e3a8397-8740-49ab-8591-d8276626c023
        position:
          posX: 621.6704282276503
          posY: 268.7888559738162
        style:
        - data:
            id: 3e1af5c1-72db-4a65-83d4-21190c16c0fe
            metadata:
              port: 6379
              protocol: TCP
            source: 6badde68-595b-4e86-9be8-61318e52b476
            subType: Network
            target: a6361bc8-7f4e-4e11-9406-e1bfd5578a53
        - data:
            id: 6985e17c-d4c0-4600-94ed-4809afe3df6f
            metadata:
              port: 6379
              protocol: TCP
            source: 7e403128-5022-409a-a1f2-26e0a5d25685
            subType: Network
            target: a6361bc8-7f4e-4e11-9406-e1bfd5578a53
        whiteboardData: {}
  redis-leader-uwufw:
    name: redis-leader
    type: Service
    apiVersion: v1
    namespace: guestbook
    model: kubernetes
    dependsOn:
    - guestbook
    settings:
      spec:
        ports:
        - port: 6379
          protocol: TCP
          target Port: 6379
        - port: 6379
          protocol: TCP
        selector:
          app: redis
          role: leader
          tier: backend
    traits:
      meshmap:
        id: 6badde68-595b-4e86-9be8-61318e52b476
        label: redis-leader
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          styleOverrides: '{"height":16,"width":17,"padding":12,"background-fit":"none","background-position-y":4.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        parent: 1e3a8397-8740-49ab-8591-d8276626c023
        position:
          posX: 528.8098398673073
          posY: 360.56548043962397
        style:
        - data:
            id: c586a713-2ded-42b5-8dba-51bda8f2be08
            metadata:
              port: 6379
              protocol: TCP
            source: 6badde68-595b-4e86-9be8-61318e52b476
            subType: Network
            target: 9407d316-5e5a-4212-8767-2bcd60c9ac17
        - data:
            id: 3e1af5c1-72db-4a65-83d4-21190c16c0fe
            metadata:
              port: 6379
              protocol: TCP
            source: 6badde68-595b-4e86-9be8-61318e52b476
            subType: Network
            target: a6361bc8-7f4e-4e11-9406-e1bfd5578a53
        whiteboardData:
          style: {}
