name: gcp-quota-exporter
services:
  NodeGroupInventoryWallet:
    name: NodeGroupInventoryWallet
    type: NodeGroupInventoryWallet
    apiVersion: core.meshery.io/v1alpha1
    version: 0.7.1
    model: meshery-core
    dependsOn:
    - gcp-quota-exporter-nvhhn
    traits:
      meshmap:
        edges: []
        id: eba097d7-3552-477b-ba90-89795b62e41f
        label: NodeGroupInventoryWallet
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          components: null
          description: ""
          displayName: Meshery Core
          hostID: 26e64aa8-2d86-57bd-92b3-2a73160d27b4
          id: 3e2db384-d3af-5fac-8af2-684fc3c29446
          metadata:
            isAnnotation: false
            subCategory: App Definition and Development
            svgColor: ui/public/static/img/meshmodels/meshery-core/color/meshery-core-color.svg
            svgComplete: ""
            svgWhite: ui/public/static/img/meshmodels/meshery-core/color/meshery-core-color.svg
          model:
            version: 0.7.1
          name: meshery-core
          registrant:
            hostname: artifacthub
          relationships: null
          schemaVersion: core.meshery.io/v1beta1
          status: enabled
          subCategory: App Definition and Development
          version: v1.0.0
        meshmodel-metadata:
          capabilities: |-
            {
              "designer": {
                "pass-events-to": "parent",
                "edit": {
                  "config": false,
                  "copy": false,
                  "delete": false,
                  "duplicate": false,
                  "reset-styles": false,
                  "resolve": false,
                  "lock": false,
                  "shape": {
                    "convert-shape": false
                  },
                  "style": false
                },
                "label": {
                  "edit": false,
                  "show": false,
                  "sync-with-config-property": "none"
                }
              }
            }
          defaultData: '{"label":""}'
          genealogy: parent
          hasInvalidSchema: true
          isAnnotation: true
          primaryColor: '#00B39F'
          secondaryColor: '#00D3A9'
          shape: round-rectangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-image: none
            background-opacity: 0.1
            border-style: dashed
            border-width: 0
            data:
              label: ""
            height: 30px
            width: 30px
            z-index: 4
          styles: '{"height":"30px","width":"30px", "background-image":"none","border-width":0,"border-style":"dashed","background-opacity":0.1}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/meshery-core/color/anchornode-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/meshery-core/white/anchornode-white.svg
        parent: 5f3e6804-3597-4a76-9acd-c4264570ddc2
        position:
          posX: 70.5
          posY: 9
        whiteboardData: {}
  gcp-quota-exporter-dqgku:
    name: gcp-quota-exporter
    type: ServiceAccount
    apiVersion: v1
    namespace: default
    model: kubernetes
    labels:
      app.kubernetes.io/instance: gcp-quota-exporter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: gcp-quota-exporter
      app.kubernetes.io/version: v0.3.2
      helm.sh/chart: gcp-quota-exporter-2.0.2
    traits:
      meshmap:
        edges: []
        id: 46c66ee2-e30c-4508-a0c9-91e59409fa82
        meshmodel-metadata:
          capabilities: ""
          defaultData: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: bottom-round-rectangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides: ""
          styles: ""
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/serviceaccount-white.svg
        position:
          posX: -29
          posY: 28
        whiteboardData:
          style: {}
  gcp-quota-exporter-mduex:
    name: gcp-quota-exporter
    type: Service
    apiVersion: v1
    namespace: default
    model: kubernetes
    labels:
      app.kubernetes.io/instance: gcp-quota-exporter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: gcp-quota-exporter
      app.kubernetes.io/version: v0.3.2
      helm.sh/chart: gcp-quota-exporter-2.0.2
    settings:
      spec:
        ports:
        - name: http
          port: 80
          protocol: TCP
          target Port: http
        selector:
          app.kubernetes.io/instance: gcp-quota-exporter
          app.kubernetes.io/name: gcp-quota-exporter
        type: ClusterIP
    traits:
      meshmap:
        edges: []
        id: 2a854baf-fd49-4313-945c-0cb751d15d9d
        meshmodel-metadata:
          capabilities: ""
          defaultData: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-position-y: 4.5
            height: 20
            padding: 12
            width: 20
            x: 10px
            "y": 12px
            z-index: 4
          styles: '{"height":20,"width":20,"padding":12,"background-position-y":4.5,"x":"10px","y":"12px"}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/service-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/service-white.svg
        position:
          posX: -23
          posY: -22
        whiteboardData:
          style: {}
  gcp-quota-exporter-nvhhn:
    name: gcp-quota-exporter
    type: Deployment
    apiVersion: apps/v1
    namespace: default
    model: kubernetes
    labels:
      app.kubernetes.io/instance: gcp-quota-exporter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: gcp-quota-exporter
      app.kubernetes.io/version: v0.3.2
      helm.sh/chart: gcp-quota-exporter-2.0.2
    settings:
      spec:
        replicas: 1
        selector:
          match Labels:
            app.kubernetes.io/instance: gcp-quota-exporter
            app.kubernetes.io/name: gcp-quota-exporter
        template:
          metadata:
            labels:
              app.kubernetes.io/instance: gcp-quota-exporter
              app.kubernetes.io/name: gcp-quota-exporter
          spec:
            containers:
            - env:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /app/credentials.json
              - name: GOOGLE_PROJECT_ID
                value: null
              image: mintel/gcp-quota-exporter:v0.3.2
              image Pull Policy: IfNotPresent
              liveness Probe:
                failure Threshold: 3
                http Get:
                  path: /metrics
                  port: http
                  scheme: HTTP
                initial Delay Seconds: 10
                period Seconds: 10
                success Threshold: 1
                timeout Seconds: 5
              name: gcp-quota-exporter
              ports:
              - container Port: 9592
                name: http
                protocol: TCP
              readiness Probe:
                failure Threshold: 3
                http Get:
                  path: /metrics
                  port: http
                  scheme: HTTP
                period Seconds: 10
                success Threshold: 1
                timeout Seconds: 5
              volume Mounts:
              - mount Path: /app/credentials.json
                name: stackdriver-service-account
                sub Path: private_key
            service Account Name: gcp-quota-exporter
            volumes:
            - name: stackdriver-service-account
              secret:
                secret Name: monitoring-v3--stackdriver
    traits:
      meshmap:
        edges: []
        id: 5f3e6804-3597-4a76-9acd-c4264570ddc2
        meshmodel-metadata:
          capabilities: |2-
             {
              "designer": {
                "edit": {
                  "shape": {
                    "convert-shape": false
                  }
                }
              }
            }
          defaultData: ""
          genealogy: parent
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: Created by Meshery Authors
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-opacity: 0.5
            border-width: 2
            z-index: 3
          styles: '{"border-width":2,"background-opacity":0.5}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/deployment-white.svg
        position:
          posX: 70.5
          posY: 9
        whiteboardData:
          style: {}
